export const productDb = [
  {
    category: "produce",
    image: "https://www.kroger.com/product/images/large/front/0000000004011",
    name: "Banana",
    price: "0.49",
  },
  {
    category: "dairy",
    image: "https://www.kroger.com/product/images/large/front/0005000032290",
    name: "Hazelnut Creamer",
    price: "3.99",
  },
  {
    category: "produce",
    image: "https://www.kroger.com/product/images/large/front/0003338320027",
    name: "Strawberries",
    price: "2.99",
  },
  {
    category: "meat",
    image: "https://www.kroger.com/product/images/large/front/0001111099000",
    name: "Turkey Burgers",
    price: "12.99",
  },
  {
    category: "meat",
    image: "https://www.kroger.com/product/images/large/front/0001111097191",
    name: "Smoked Bacon",
    price: "5.49",
  },
  {
    category: "produce",
    image: "https://www.kroger.com/product/images/large/front/0000000004225",
    name: "Large Avocado",
    price: "1.67",
  },
  {
    category: "dairy",
    image: "https://www.kroger.com/product/images/large/front/0068954408301",
    name: "Plain Greek Yogurt",
    price: "5.39",
  },
  {
    category: "dairy",
    image: "https://www.kroger.com/product/images/large/front/0002100060464",
    name: "Kraft SINGLES",
    price: "3.49",
  },
  {
    category: "dairy",
    image: "https://www.kroger.com/product/images/large/front/0001111041700",
    name: "2% Milk",
    price: "2.99",
  },
  {
    category: "meat",
    image: "https://www.kroger.com/product/images/large/front/0001111097920",
    name: "1lb Ground Beef",
    price: "3.79",
  },
  {
    category: "produce",
    image: "https://www.kroger.com/product/images/large/front/0000000003283",
    name: "Honeycrisp Apple",
    price: "1.35",
  },
  {
    category: "meat",
    image: "https://www.kroger.com/product/images/large/front/0026082900000",
    name: "1lb Chicken Breasts",
    price: "6.63",
  },
  {
    category: "meat produce",
    image: "https://i.imgur.com/57h22vq.jpg",
    name: "Banausage",
    price: "6.66",
  },
  {
    category: "produce",
    image:
      "https://preview.redd.it/qnccx3yleob31.jpg?width=960&crop=smart&auto=webp&s=42f61cee572052cf361662e7cc23da6ba25cfa37",
    name: "Eggo Real Fruit Pizza",
    price: "3.29",
  },
  {
    category: "produce dairy",
    image: "https://www.kroger.com/product/images/large/front/0001111009345",
    name: "Spanakopita",
    price: "8.49",
  },
  {
    category: "meat",
    image: "https://m.media-amazon.com/images/I/61jQ2n3ILKL._SL1440_.jpg",
    name: "Buffalo Wing Soda",
    price: "2.99",
  },
  {
    category: "meat",
    image: "https://m.media-amazon.com/images/I/61-njaOgxcL._SL1280_.jpg",
    name: "Wild Burgundy Snails",
    price: "31.99",
  },
];
